apiVersion: v1
kind: Service
metadata:
  name: keydb
spec:
  selector:
    app: keydb
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
        - name: keydb
          image: eqalpha/keydb:latest
          ports:
            - containerPort: 6379
