apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: local/basedbeanserver:v1
          imagePullPolicy: Never
          workingDir: /app
          command: ["./server"]
          ports:
            - containerPort: 8090
          env:
            - name: MONGODB_SCHEME
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_IP
              value: "mongo-service"
            - name: KEG_SCHEME
              value: "http"
            - name: KEG_PORT
              value: "8080"
            - name: KEG_IP
              value: "keg-service"
            - name: SERVER_PORT
              value: "8090"
            - name: SERVER_IP
              value: "0.0.0.0"
            - name: JWT_SECRET
              value: "supersecretkey"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: expiry-checker
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: curlimages/curl:latest
              command: ["curl"]
              args: ["-X", "GET", "http://server-service:8090/expiry"]
          restartPolicy: OnFailure
